name: CI
on: [push, pull_request]
jobs:
  unit-tests:
    name: Unit Tests (API)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - run: cd api && yarn
      - name: Unit Tests
        run: cd api && npm run test:unit
  integration-tests:
    name: Integration Tests (API)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - run: cd api && yarn
      - name: Integration Tests
        run: cd api && npm run test:integration
